import type { Metadata } from 'next'
import '@/app/styles/index.scss'

import { Roboto } from 'next/font/google'
import { Dock } from '@/shared/ui'
import { Providers } from '@/app/providers/queryProvider'
import { ThemeProvider } from '@/shared/providers/ThemeProvider'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body>
        <ThemeProvider>
          <Providers>
            <div className="container">{children}</div>
            <Dock />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
