import type { Metadata } from 'next'
import '@/app/styles/index.scss'

import { Roboto } from 'next/font/google'
import ReduxProvider from './store/providers/provider'

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={`${roboto.variable}`}>
            <body>
                <ReduxProvider>
                    <div className="container">{children}</div>
                </ReduxProvider>
            </body>
        </html>
    )
}
